server:
  tomcat:
    uri-encoding: UTF-8
  port: 6001
spring:
  profiles:
    active: dev
  application:
    name: mopsz-soft-search
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true