server:
  tomcat:
    uri-encoding: UTF-8
  port: 5002
spring:
  profiles:
    active: dev
  application:
    name: mopsz-cloud-gateway
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true