server:
  tomcat:
    uri-encoding: UTF-8
  port: 6002
spring:
  profiles:
    active: dev
  application:
    name: mopsz-soft-rocket
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true