spring:
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000ms
    jedis:
      pool:
        max-active: 200
        max-idle: 200
        min-idle: 0
        max-wait: 3000
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
      service-url:
        defaultZone: http://127.0.0.1:5001/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 60000
        readTimeout: 60000