server:
  tomcat:
    uri-encoding: UTF-8
  port: 6801
spring:
  profiles:
    active: dev
  application:
    name: mopsz-data-analy
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/reportMapper/*.xml
  typeAliasesPackage: com.husky.cloud.*.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'